final Map<String, String> subjectMap = {
  "Accounting": "Accounting",
  "Accounts Law": "Accounts Law",
  "Agency Law": "Agency Law",
  "Alternative Dispute Resolution (ADR)/Mediation": "Alternative Dispute Resolution (ADR)/Mediation",
  "Anthropology": "Anthropology",
  "Archaeology": "Archaeology",
  "Architecture": "Architecture",
  "Art": "Art",
  "Biology": "Biology",
  "Business": "Business",
  "Chemistry": "Chemistry",
  "Children & Young People": "Children & Young People",
  "Civil Litigation Law": "Civil Litigation Law",
  "Commercial Law": "Commercial Law",
  "Commercial Property Law": "Commercial Property Law",
  "Communications": "Communications",
  "Company/Business/Partnership Law": "Company/Business/Partnership Law",
  "Comparative Law": "Comparative Law",
  "Competition Law": "Competition Law",
  "Computer Science": "Computer Science",
  "Constitutional/Administrative Law": "Constitutional/Administrative Law",
  "Construction": "Construction",
  "Consumer Law": "Consumer Law",
  "Contract Law": "Contract Law",
  "Corporate Finance": "Corporate Finance",
  "Counseling": "Counseling",
  "Criminal Law": "Criminal Law",
  "Criminal Litigation": "Criminal Litigation",
  "Criminology": "Criminology",
  "Cultural Studies": "Cultural Studies",
  "Cybernetics": "Cybernetics",
  "Design": "Design",
  "Dental": "Dental",
  "Drama": "Drama",
  "Economics": "Economics",
  "Econometrics": "Econometrics",
  "Education": "Education",
  "Employment": "Employment",
  "Employment Law": "Employment Law",
  "Engineering": "Engineering",
  "English Language": "English Language",
  "English Literature": "English Literature",
  "Environment": "Environment",
  "Environmental Law": "Environmental Law",
  "Environmental Sciences": "Environmental Sciences",
  "Equity Law": "Equity Law",
  "Estate Management": "Estate Management",
  "European Law": "European Law",
  "European Studies": "European Studies",
  "Eviews": "Eviews",
  "Family Law": "Family Law",
  "Fashion": "Fashion",
  "Film Studies": "Film Studies",
  "Finance": "Finance",
  "Finance Law": "Finance Law",
  "Food and Nutrition": "Food and Nutrition",
  "Forensic Science": "Forensic Science",
  "French": "French",
  "General Law": "General Law",
  "Geography": "Geography",
  "Geology": "Geology",
  "German": "German",
  "Health": "Health",
  "Health & Social Care": "Health & Social Care",
  "Health and Safety": "Health and Safety",
  "Health and Safety Law": "Health and Safety Law",
  "History": "History",
  "Holistic/Alternative Therapy": "Holistic/Alternative Therapy",
  "Housing": "Housing",
  "Housing Law": "Housing Law",
  "Human Resource Management": "Human Resource Management",
  "Human Rights": "Human Rights",
  "HR": "HR",
  "Immigration/Refugee Law": "Immigration/Refugee Law",
  "Information - Media & Technology Law": "Information - Media & Technology Law",
  "Information Systems": "Information Systems",
  "Information Technology": "Information Technology",
  "IT": "IT",
  "Intellectual Property Law": "Intellectual Property Law",
  "International Business": "International Business",
  "International Commercial Law": "International Commercial Law",
  "International Law": "International Law",
  "International Political Economy": "International Political Economy",
  "International Relations": "International Relations",
  "International Studies": "International Studies",
  "Jurisprudence": "Jurisprudence",
  "Land/Property Law": "Land/Property Law",
  "Landlord & Tenant Law": "Landlord & Tenant Law",
  "Law of Evidence": "Law of Evidence",
  "Life Sciences": "Life Sciences",
  "Linguistics": "Linguistics",
  "Logistics": "Logistics",
  "Management": "Management",
  "Maritime Law": "Maritime Law",
  "Marketing": "Marketing",
  "Mathematics": "Mathematics",
  "Media": "Media",
  "Medical Law": "Medical Law",
  "Medical Technology": "Medical Technology",
  "Medicine": "Medicine",
  "Mental Health": "Mental Health",
  "Mental Health Law": "Mental Health Law",
  "Methodology": "Methodology",
  "Music": "Music",
  "Negligence Law": "Negligence Law",
  "Nursing": "Nursing",
  "Occupational Therapy": "Occupational Therapy",
  "Operations": "Operations",
  "Pharmacology": "Pharmacology",
  "Philosophy": "Philosophy",
  "Photography": "Photography",
  "Physical Education": "Physical Education",
  "Physics": "Physics",
  "Planning/Environmental Law": "Planning/Environmental Law",
  "Politics": "Politics",
  "Project Management": "Project Management",
  "Professional Conduct Law": "Professional Conduct Law",
  "Psychology": "Psychology",
  "Psychotherapy": "Psychotherapy",
  "Public Administration": "Public Administration",
  "Public Health": "Public Health",
  "Public Law": "Public Law",
  "Quantity Surveying": "Quantity Surveying",
  "Real Estate": "Real Estate",
  "Restitution Law": "Restitution Law",
  "Shipping Law": "Shipping Law",
  "Social Policy": "Social Policy",
  "Social Work": "Social Work",
  "Social Work Law": "Social Work Law",
  "Sociology": "Sociology",
  "Spanish": "Spanish",
  "Sports": "Sports",
  "Sports Law": "Sports Law",
  "Sports Science": "Sports Science",
  "SPSS": "SPSS",
  "Statistics": "Statistics",
  "Succession Law": "Succession Law",
  "Supply Chain": "Supply Chain",
  "Tax Law": "Tax Law",
  "Teacher Training": "Teacher Training",
  "Theatre Studies": "Theatre Studies",
  "Theology & Religion": "Theology & Religion",
  "Tort Law": "Tort Law",
  "Tourism": "Tourism",
  "Town & Country Planning": "Town & Country Planning",
  "Translation": "Translation",
  "Trusts Law": "Trusts Law",
  "Wills/Probate Law": "Wills/Probate Law",
  "Economics (Social Sciences)": "Economics (Social Sciences)",
  "Other": "Other"
};
